from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[]
    operations=[
        migrations.CreateModel(name='Acara',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('nama',models.CharField(max_length=200)),('sub_acara',models.CharField(blank=True,max_length=200)),('tanggal_mulai',models.DateTimeField()),('tanggal_selesai',models.DateTimeField(blank=True,null=True)),('lokasi',models.CharField(blank=True,max_length=200)),('status',models.CharField(default='Belum Dimulai',max_length=50)),('deskripsi',models.TextField(blank=True)),('urutan',models.PositiveIntegerField(default=0))],options={'ordering':['urutan','tanggal_mulai']}),
        migrations.CreateModel(name='Kelompok',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('nama',models.CharField(max_length=100,unique=True)),('mentor',models.CharField(blank=True,max_length=200)),('progress',models.PositiveIntegerField(default=0)),('catatan',models.TextField(blank=True))]),
        migrations.CreateModel(name='Pengumuman',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('judul',models.CharField(max_length=200)),('isi',models.TextField()),('aktif',models.BooleanField(default=True)),('dibuat',models.DateTimeField(auto_now_add=True))],options={'ordering':['-dibuat']}),
        migrations.CreateModel(name='Setting',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('nama_praktikum',models.CharField(default='Praktikum Perencanaan Tambang',max_length=200)),('periode',models.CharField(default='2026/2027',max_length=100)),('deskripsi',models.TextField(blank=True)),('dosen_pengampu',models.CharField(blank=True,max_length=200)),('koordinator',models.CharField(blank=True,max_length=200)),('kontak',models.CharField(blank=True,max_length=200)),('updated_at',models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='Staff',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('nama',models.CharField(max_length=200)),('jabatan',models.CharField(choices=[('koordinator','Koordinator Asisten Dosen'),('asisten','Asisten Dosen')],max_length=30)),('kontak',models.CharField(blank=True,max_length=100))]),
        migrations.CreateModel(name='TataTertib',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('judul',models.CharField(max_length=200)),('isi',models.TextField()),('aktif',models.BooleanField(default=True)),('urutan',models.PositiveIntegerField(default=0))],options={'ordering':['urutan','id']}),
        migrations.CreateModel(name='Peserta',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('nama',models.CharField(max_length=200)),('nim',models.CharField(blank=True,max_length=50)),('email',models.EmailField(blank=True,max_length=254)),('aktif',models.BooleanField(default=True)),('kelompok',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='peserta',to='praktikum.kelompok'))]),
        migrations.CreateModel(name='Materi',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('judul',models.CharField(max_length=200)),('kategori',models.CharField(choices=[('modul','Modul'),('dataset','Dataset'),('template','Template'),('lainnya','Lainnya')],default='modul',max_length=30)),('file',models.FileField(upload_to='materi/%Y/%m/')),('deskripsi',models.TextField(blank=True)),('uploaded_at',models.DateTimeField(auto_now_add=True)),('acara',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='praktikum.acara'))]),
        migrations.CreateModel(name='Absensi',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('status',models.CharField(choices=[('H','Hadir'),('I','Izin'),('S','Sakit'),('A','Alfa')],default='H',max_length=1)),('catatan',models.CharField(blank=True,max_length=200)),('acara',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='absensi',to='praktikum.acara')),('peserta',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='absensi',to='praktikum.peserta'))],options={'unique_together':{('peserta','acara')}}),
    ]
